<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>Detroit Audio Extractor</AssemblyName><ApplicationIcon>../../Audio/DAEIcon.ico</ApplicationIcon></PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>Detroit Audio Extractor</AssemblyTitle>
    <Title>Detroit Audio Extractor</Title>
    <Product>Detroit Audio Extractor</Product>
    <Description>Tool to extract audio files from the game "Detroit: Become Human"</Description>
    <Authors>root-mega, BalancedLight</Authors>
    <Company>Detroit: Become Human Readable</Company>
    <Version>1.0.0</Version>
    <PackageVersion>1.0.0</PackageVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../DetroitAudio.Indexing/DetroitAudio.Indexing.csproj" /><ProjectReference Include="../DetroitAudio.Export/DetroitAudio.Export.csproj" /><PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" /><PackageReference Include="NAudio" Version="2.2.1" /></ItemGroup>
  <ItemGroup><Resource Include="../../Audio/detroitread.png" Link="Assets/Logo.png" /></ItemGroup>
  <Import Project="../../build/AutoPublish.targets" />
</Project>
